### ISSUE TITLE
ERROR: Service 'php' failed to build:

### ISSUE THREAD

**Issue by flik** [Phillaf/php-kafka-demo#2]
`
ERROR: `/tmp/pear/temp/rdkafka/configure --with-php-config=/usr/local/bin/php-config' failed
ERROR: Service 'php' failed to build: The command '/bin/sh -c git clone --depth 1 --branch v0.9.5 https://github.com/edenhill/librdkafka.git     && (         cd librdkafka         && ./configure         && make         && make install     )     && pecl install rdkafka     && echo "extension=rdkafka.so" > /usr/local/etc/php/conf.d/rdkafka.ini' returned a non-zero code: 1

`

**Comment by g-ra** [comment]
change The command '/bin/sh -c git clone --depth 1 --branch v0.9.5 => The command '/bin/sh -c git clone --depth 1 --branch v0.11.1
